language: cpp
compiler:
  - gcc
  - clang
env:
  - CXXSTD=c++11
  - CXXSTD=c++1y
before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev g++-4.8 cppcheck doxygen
  - sudo sed -i -e 's|friend class hash|friend struct hash|' /usr/include/c++/4.8/bits/stl_bvector.h
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - cmake . -DSDL2PP_ENABLE_LIVE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=`pwd`.prefix -DSDL2PP_WITH_WERROR=YES -DSDL2PP_CXXSTD=$CXXSTD
  - VERBOSE=1 make && make test && make install
  - cppcheck -I . --enable=style,performance,portability,information,missingInclude --error-exitcode=2 SDL2pp
  - "if make doxygen 2>&1 | grep 'warning:'; then echo 'FATAL: doxygen warnings!'; false; fi"
  - "if git ls-files --others --exclude-standard | grep ''; then echo 'FATAL: incomplete .gitignore'; false; fi"
